# Generated by Django 3.2.18 on 2023-04-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=250)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'quests',
            },
        ),
    ]
